#!/bin/env bash

for item in $(find src -regextype sed -regex ".*\.[ch]pp"); do
	echo "Formatting $item"
	clang-tidy -checks='readability-braces-around-statements' -fix \
		$item -- -Isrc/include --std=c++20
	clang-format -i $item
done
